### PR TITLE
feat: update to probot v12

### PR DESCRIPTION
**Pull request by cjorge-graphops**
Probot v9 doesn't seem to work anymore (deprecated APIs reaching EOL), so maybe refresh this to more recent versions?

### CODE REVIEW

**Comment by rarkins** [comment]
Have you been able to test/validate that this works locally? i.e. you're running it "in production" already?

**Comment by cjorge-graphops** [comment]
> Have you been able to test/validate that this works locally? i.e. you're running it "in production" already?

@rarkins not exhaustively yet, i.e. I'm running it to approve PRs and that code path is working well. I haven't actually tested the re-approve after dismissal path, but I will do so and report back! Thanks for the swift reply :bow:

**Comment by cjorge-graphops** [comment]
@rarkins I have now also tested the dismiss / re-approve flow and that too is seemingly working as intended

**Comment by cjorge-graphops** [comment]
@rarkins anything I can do to further help move this forward? :)

**Comment by rarkins** [comment]
Thanks for the PR!

**Pull request merged**
